# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'BottomSheetControllerDemo' do
  use_frameworks!

  pod 'BottomSheetController', :path => '../BottomSheetController'

end
